<a href="https://colab.research.google.com/github/ayushharshit999/FakeNewsClassifier/blob/main/fake_news_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imported the csv file of news headlines in the form of dataframe

In [1]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/fake-news/data.csv')
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [2]:
df=df.dropna()

In [4]:
X = df.drop(['label'],axis=1)
y= df['label']

In [5]:
X.shape

(18285, 4)

In [6]:
y.shape

(18285,)

Imported all the necessary libraries

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
import nltk
import re
from nltk.corpus import stopwords

Data Preprocessing

In [8]:
voc_size=5000
messages=X.copy()
messages.reset_index(inplace=True)


In [9]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [10]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [11]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

One hot encoding

In [12]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[3290, 1134, 319, 2815, 1034, 2123, 283, 2502, 4567, 4134],
 [760, 1896, 1486, 2851, 1910, 4889, 4217],
 [1640, 4214, 1927, 2223],
 [3215, 1244, 4776, 2883, 1209, 1191],
 [1327, 1910, 471, 3468, 1815, 131, 1910, 2201, 2109, 2836],
 [1361,
  1656,
  3930,
  4626,
  961,
  1513,
  3249,
  2804,
  2327,
  4087,
  4631,
  1354,
  1784,
  4058,
  4217],
 [135, 111, 298, 4871, 4329, 2180, 325, 4440, 4628, 2183, 756],
 [991, 2762, 4443, 1065, 2858, 3794, 1513, 1398, 4628, 2183, 756],
 [547, 2003, 4580, 3362, 1159, 1847, 2903, 1469, 1513, 4258],
 [3914, 720, 2645, 4374, 3899, 3870, 4254, 116],
 [1938, 1385, 1585, 4248, 4038, 2347, 3364, 4518, 379, 3763, 3168],
 [2883, 1274, 1034, 1847, 1513, 2858],
 [4803, 1582, 19, 994, 2266, 2794, 955, 3685, 287],
 [2721, 3264, 397, 115, 3721, 4205, 4292, 4628, 2183, 756],
 [2396, 768, 3212, 122, 2212, 4628, 2183, 756],
 [3206, 1170, 4612, 1886, 3805, 1140, 2896, 2173, 2034, 1527],
 [1308, 4639, 1896],
 [2286, 4918, 3544, 2075, 1513, 2623, 3417, 4217],
 [30

Word Embedding

In [13]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2502 4567 4134]
 [   0    0    0 ... 1910 4889 4217]
 [   0    0    0 ... 4214 1927 2223]
 ...
 [   0    0    0 ... 4628 2183  756]
 [   0    0    0 ... 2572 1281 4679]
 [   0    0    0 ... 2910  799 1190]]


Creating the Model

In [14]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


Converting the data frame to np array so that it would be compatible for the model

In [17]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)
X_final.shape,y_final.shape

((18285, 20), (18285,))

Splitting the data into train and test with 67 % for training and 33 percent for testing

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

Applying the model

In [19]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 25s 89ms/step - loss: 0.3277 - accuracy: 0.8409 - val_loss: 0.1990 - val_accuracy: 0.9163
Epoch 2/10
192/192 [==============================] - 3s 16ms/step - loss: 0.1346 - accuracy: 0.9462 - val_loss: 0.2077 - val_accuracy: 0.9072
Epoch 3/10
192/192 [==============================] - 3s 15ms/step - loss: 0.0953 - accuracy: 0.9654 - val_loss: 0.2260 - val_accuracy: 0.9133
Epoch 4/10
192/192 [==============================] - 2s 12ms/step - loss: 0.0657 - accuracy: 0.9771 - val_loss: 0.2595 - val_accuracy: 0.9105
Epoch 5/10
192/192 [==============================] - 3s 14ms/step - loss: 0.0440 - accuracy: 0.9856 - val_loss: 0.3195 - val_accuracy: 0.9162
Epoch 6/10
192/192 [==============================] - 2s 11ms/step - loss: 0.0237 - accuracy: 0.9923 - val_loss: 0.4015 - val_accuracy: 0.9114
Epoch 7/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0143 - accuracy: 0.9958 - val_loss: 0.3944 - val_accuracy: 0.9183

In [30]:
y_pred=model.predict(X_test)
y_pred = np.round(y_pred)

189/189 [==============================] - 0s 2ms/step


In [31]:
y_pred

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [1.]], dtype=float32)

Accuracy Score on test portion

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9116818558409279